name: Build and Test

on:
  push:
    branches:
      - master # or your main development branch
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x] # Test across multiple Node.js versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Caches node modules to speed up builds

      - name: Install dependencies
        run: npm ci # Use npm ci for clean installs (recommended for CI/CD)

      - name: Run tests
        run: npm test

      - name: Build for production
        run: npm run build

      - name: Artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: ./build # This is the directory your `npm run build` produces

  # example deploy job
  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: production-build
  #         path: ./build_to_deploy
  #     - name: Deploy to hosting provider
  #       #... your deployment steps here
  #       run: |
  #         echo "Implement deployment here"
  #         ls -l build_to_deploy
